before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y inotify-tools
language: elixir
matrix:
  include:
    - elixir: 1.3.4
      otp_release: 19.1
    - elixir: 1.4.1
      otp_release: 19.1
    - elixir: 1.5.1
      otp_release: 20.0
after_success:
- curl -H "Content-Type: application/json" --data '{"docker_tag": "master"}' -X POST https://registry.hub.docker.com/u/krlsdu/elixir-koans/trigger/${TOKEN_DOCKER_BUILD}/
