before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y inotify-tools
language: elixir
matrix:
  include:
    - elixir: 1.3.4
      otp_release: 19.1
    - elixir: 1.4.1
      otp_release: 19.1
    - elixir: 1.5.1
      otp_release: 20.0
    - elixir: 1.6.5
      otp_release: 20.0
    - elixir: 1.7.3
      otp_release: 21.0
